//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 20
        ///0	0	0	0	00:00:00	0
        ///60000	75000	60000	80	10:00:00.
        /// </summary>
        internal static string academy {
            get {
                return ResourceManager.GetString("academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///80	30	60	1	00:03:00.
        /// </summary>
        internal static string archer {
            get {
                return ResourceManager.GetString("archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5
        ///60	30	40	1	00:02:30.
        /// </summary>
        internal static string axefighter {
            get {
                return ResourceManager.GetString("axefighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 2
        ///0	0	0	0	00:00:00	0
        ///400	500	600	7	00:01:00	100
        ///480	600	720	1	00:02:30	100
        ///580	720	860	2	00:04:00	100
        ///700	860	1030	2	00:05:30	100
        ///840	1030	1240	3	00:07:00	100
        ///1800	2000	2200	2	00:08:30	100
        ///2200	2400	2600	4	00:10:00	100
        ///2600	2900	3100	4	00:12:00	100
        ///3100	3500	3700	5	00:14:00	100
        ///3700	4200	4400	6	00:16:00	95
        ///6000	7000	8000	7	00:18:00	95
        ///7200	8400	9600	9	00:20:00	95
        ///8600	10100	11500	10	00:25:00	95
        ///10300	12100	13800	13	00:30:00	95
        ///12400	14500	16600	15	00:45:00	95
        ///21000	23000	25000	18	01:00:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string barracks {
            get {
                return ResourceManager.GetString("barracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17
        ///320	400	100	8	00:07:30.
        /// </summary>
        internal static string catapult {
            get {
                return ResourceManager.GetString("catapult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 1
        ///0	0	0	0	00:00:00	0
        ///160	200	50	0	00:00:30	100.
        /// </summary>
        internal static string chapel {
            get {
                return ResourceManager.GetString("chapel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 1
        ///0	0	0	0	00:00:00	0
        ///1	16000	20000	5000	5000	06:00:00	100
        ///2	20000	25000	7000	7750	15:00:00	105
        ///3	25000	25000	32000	12013	24:00:00	110.
        /// </summary>
        internal static string church {
            get {
                return ResourceManager.GetString("church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 1
        ///0	0	0	0	00:00:00	20
        ///50	40	30	1	00:00:30	120
        ///60	50	40	1	00:01:00	132
        ///80	60	50	2	00:01:30	146
        ///100	80	60	2	00:02:00	162
        ///100	100	70	2	00:02:30	180
        ///200	100	90	2	00:03:30	200
        ///200	200	100	3	00:05:00	222
        ///200	200	100	3	00:10:00	248
        ///300	200	200	4	00:20:00	276
        ///400	300	200	4	00:30:00	308
        ///500	400	300	4	00:40:00	343
        ///600	500	300	5	00:50:00	383
        ///700	600	400	6	01:00:00	429
        ///900	700	500	7	01:15:00	480
        ///1000	900	700	8	01:30:00	536
        ///1000	1000	800	8	01:45:00	600
        ///2000	1000	1000	10	02:00:00	673
        ///2000	2000	1000	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string claypit {
            get {
                return ResourceManager.GetString("claypit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 1
        ///0	0	0	0	00:00:00	0
        ///40	50	30	0	00:01:00	240
        ///50	70	40	0	00:01:30	281
        ///70	90	50	0	00:02:00	330
        ///90	110	70	0	00:05:00	386
        ///120	150	90	0	00:07:30	453
        ///150	190	120	0	00:10:00	531
        ///200	250	150	0	00:30:00	622
        ///260	330	200	0	00:40:00	729
        ///350	430	260	0	00:50:00	855
        ///500	600	300	0	01:00:00	1002
        ///600	700	400	0	01:15:00	1175
        ///800	1000	600	0	01:30:00	1377
        ///1000	1300	800	0	01:45:00	1614
        ///1300	1700	1000	0	02:00:00	1891
        ///1800	2200	1300	0	02:30:00	2217
        ///2300	2900	1700	0	03:00:00	2598
        ///3000	3800	2300	0	03:30:00	3046        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string farm {
            get {
                return ResourceManager.GetString("farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 25
        ///0	0	0	0	00:00:00	0
        ///35000	50000	30000	11	01:00:00	1
        ///42000	58500	36900	14	02:00:00	2
        ///50400	68445	45387	17	03:00:00	3
        ///60480	80081	55826	21	05:00:00	4
        ///72576	93694	68666	28	08:00:00	5
        ///87091	109622	84459	35	12:00:00	6
        ///104509	128258	103885	45	16:00:00	7
        ///125411	150062	127778	56	21:00:00	8
        ///150494	175573	157167	72	28:00:00	9
        ///180592	205420	193316	92	36:00:00	10.
        /// </summary>
        internal static string halloforders {
            get {
                return ResourceManager.GetString("halloforders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 1
        ///0	0	0	0	00:00:00	0
        ///0	0	0	1	00:00:30	30
        ///700	750	650	1	00:02:00	60
        ///1000	1300	900	1	00:03:00	90
        ///1400	1500	1300	1	00:05:00	120
        ///1900	2000	1800	1	00:07:00	150
        ///2300	2500	2100	2	00:09:00	180
        ///2800	3000	2600	2	00:12:00	210
        ///3800	4000	3600	2	00:15:00	240
        ///4800	5000	4600	3	00:18:00	270
        ///5600	6000	5200	3	00:21:00	300
        ///7600	8000	7200	3	00:25:00	330
        ///9000	10000	8000	4	00:30:00	360
        ///14000	15000	13000	5	00:35:00	390
        ///19000	20000	18000	5	00:45:00	420
        ///23000	25000	20000	7	01:00:00	450
        ///27000	30000	22000	8	01:30:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string headquarters {
            get {
                return ResourceManager.GetString("headquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///200	150	600	6	00:10:00.
        /// </summary>
        internal static string heavycavalry {
            get {
                return ResourceManager.GetString("heavycavalry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 4
        ///0	0	0	0	00:00:00	0
        ///50	80	30	2	00:03:00	100
        ///100	160	60	3	00:05:00	129
        ///200	320	120	3	00:10:00	167
        ///400	640	240	4	00:15:00	215
        ///1000	1600	600	5	00:30:00	278
        ///2000	3200	1200	7	01:00:00	359
        ///4000	6400	2400	8	02:00:00	464
        ///8000	12000	4800	11	04:00:00	599
        ///16000	24000	9600	14	12:00:00	774
        ///32000	48000	19200	17	24:00:00	1000.
        /// </summary>
        internal static string hospital {
            get {
                return ResourceManager.GetString("hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 1
        ///0	0	0	0	00:00:00	20
        ///60	50	60	1	00:00:30	120
        ///70	60	70	2	00:01:00	132
        ///90	80	90	2	00:01:30	146
        ///100	100	100	2	00:02:00	162
        ///100	100	100	3	00:02:30	180
        ///200	200	200	3	00:03:30	200
        ///200	200	200	4	00:05:00	222
        ///300	200	300	4	00:10:00	248
        ///400	300	400	5	00:20:00	276
        ///400	400	400	6	00:30:00	308
        ///500	500	500	7	00:40:00	343
        ///700	600	700	8	00:50:00	383
        ///800	700	800	10	01:00:00	429
        ///1000	900	1000	11	01:15:00	480
        ///1000	1000	1000	13	01:30:00	536
        ///2000	1000	2000	15	01:45:00	600
        ///2000	2000	2000	18	02:00:00	673
        ///30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ironmine {
            get {
                return ResourceManager.GetString("ironmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11
        ///125	100	250	4	00:06:00.
        /// </summary>
        internal static string lightcavalry {
            get {
                return ResourceManager.GetString("lightcavalry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 6
        ///0	0	0	0	00:00:00	0
        ///100	100	100	20	00:05:00	1
        ///130	130	130	3	00:15:00	2
        ///160	160	160	4	00:25:00	3
        ///200	210	200	5	00:35:00	4
        ///250	260	250	5	00:50:00	5
        ///320	340	320	7	01:10:00	6
        ///400	430	400	7	01:30:00	7
        ///500	550	500	9	01:50:00	8
        ///640	700	640	10	02:10:00	9
        ///800	890	800	12	02:30:00	10
        ///1000	1100	1000	14	03:00:00	11
        ///1300	1400	1300	16	03:30:00	14
        ///1600	1800	1600	20	04:00:00	19
        ///2000	2400	2000	22	04:30:00	26
        ///2500	3000	2500	26	05:00:00	35
        ///3200	3800	3200	31	05:50:00	46
        ///4000	4900	4000	36	06:40:00	59
        ///5100	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string market {
            get {
                return ResourceManager.GetString("market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13
        ///250	200	100	5	00:07:30.
        /// </summary>
        internal static string mountedarcher {
            get {
                return ResourceManager.GetString("mountedarcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warehouse 19
        ///farm 14
        ///headquarters 13
        ///timbercamp 25
        ///claypit 25
        ///ironmine 25
        ///barracks 9
        ///spearman 40
        ///swordsman 40.
        /// </summary>
        internal static string nsqueue {
            get {
                return ResourceManager.GetString("nsqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warehouse 19
        ///farm 14
        ///headquarters 13
        ///timbercamp 25
        ///claypit 25
        ///ironmine 25
        ///barracks 9
        ///spearman 40
        ///swordsman 40.
        /// </summary>
        internal static string nsqueue_test_1 {
            get {
                return ResourceManager.GetString("nsqueue_test_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 1
        ///0	0	0	0	00:00:00	0
        ///50	100	50	1	00:00:30	0
        ///100	150	150	1	00:05:00	0
        ///2500	2500	3000	3	08:00:00	0
        ///6000	9000	11000	7	16:00:00	0
        ///13000	18000	25000	16	24:00:00	0.
        /// </summary>
        internal static string rallypoint {
            get {
                return ResourceManager.GetString("rallypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///300	200	200	5	00:08:00.
        /// </summary>
        internal static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///50	30	20	1	00:01:30.
        /// </summary>
        internal static string spearman {
            get {
                return ResourceManager.GetString("spearman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 3
        ///0	0	0	0	00:00:00	0
        ///100	100	200	0	00:02:00	0
        ///500	500	1000	0	00:10:00	0
        ///2000	2000	4000	0	01:00:00	0
        ///5000	5000	10000	0	04:00:00	0
        ///10000	10000	20000	0	08:00:00	0.
        /// </summary>
        internal static string statue {
            get {
                return ResourceManager.GetString("statue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///30	30	70	1	00:02:00.
        /// </summary>
        internal static string swordsman {
            get {
                return ResourceManager.GetString("swordsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 8
        ///0	0	0	0	00:00:00	0
        ///150	100	110	2	00:05:00	1
        ///200	130	140	3	00:10:00	1
        ///250	170	180	3	00:20:00	2
        ///330	230	230	4	00:40:00	2
        ///430	300	300	6	01:00:00	2
        ///560	400	380	7	01:40:00	3
        ///720	530	480	9	02:20:00	3
        ///940	700	620	11	03:30:00	3
        ///1200	900	790	15	05:00:00	4
        ///1600	1200	1000	18	07:00:00	4
        ///2100	1600	1300	23	09:00:00	4
        ///2700	2100	1700	30	11:00:00	5
        ///3500	2800	2100	37	14:00:00	5
        ///4500	3700	2700	48	18:00:00	5
        ///5900	4900	3500	60	24:00:00	5.
        /// </summary>
        internal static string tavern {
            get {
                return ResourceManager.GetString("tavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 1
        ///0	0	0	0	00:00:00	20
        ///40	50	30	1	00:00:30	120
        ///50	60	40	1	00:01:00	132
        ///60	80	50	1	00:01:30	146
        ///80	100	60	1	00:02:00	162
        ///100	120	70	1	00:02:30	180
        ///100	200	100	1	00:03:30	200
        ///200	200	100	2	00:05:00	222
        ///200	200	100	2	00:10:00	248
        ///200	300	200	2	00:20:00	276
        ///300	400	200	2	00:30:00	308
        ///400	500	300	3	00:40:00	343
        ///500	600	300	3	00:50:00	383
        ///600	700	400	4	01:00:00	429
        ///700	900	500	5	01:15:00	480
        ///900	1000	700	5	01:30:00	536
        ///1000	1000	800	5	01:45:00	600
        ///1000	2000	1000	7	02:00:00	673
        ///2000	2000	1000	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timbercamp {
            get {
                return ResourceManager.GetString("timbercamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 5
        ///0	0	0	0	00:00:00	0
        ///50	100	20	5	00:02:30	5
        ///60	130	30	1	00:05:00	10
        ///80	160	30	1	00:15:00	15
        ///100	210	40	1	00:30:00	20
        ///130	260	50	1	00:50:00	25
        ///160	340	60	2	01:20:00	30
        ///200	430	80	2	02:00:00	35
        ///250	550	100	2	03:00:00	40
        ///320	700	130	3	04:00:00	45
        ///400	890	160	3	05:00:00	50
        ///500	1100	200	3	06:00:00	55
        ///640	1400	250	4	07:00:00	60
        ///800	1800	320	5	09:00:00	65
        ///1000	2400	400	5	12:00:00	70
        ///1300	3000	510	7	14:00:00	75
        ///1600	3800	640	8	18:00:00	80
        ///2000	4900	810	9	22:00:00	85
        ///2500	6200	1000	10	26:00:00  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wall {
            get {
                return ResourceManager.GetString("wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 1
        ///0	0	0	0	00:00:00	0
        ///200	190	170	0	00:00:30	1000
        ///240	230	210	0	00:01:00	1229
        ///290	280	250	0	00:01:30	1512
        ///350	340	300	0	00:02:00	1859
        ///430	410	360	0	00:02:30	2285
        ///520	490	440	0	00:04:00	2810
        ///630	600	530	0	00:06:00	3454
        ///760	720	650	0	00:10:00	4247
        ///920	870	780	0	00:20:00	5222
        ///1100	1100	900	0	00:40:00	6420
        ///1300	1300	1100	0	01:00:00	7893
        ///1600	1500	1400	0	01:30:00	9705
        ///2000	1900	1700	0	02:00:00	11932
        ///2400	2300	2000	0	02:30:00	14670
        ///2900	2700	2500	0	03:00:00	18037
        ///3500	3300	3000	0	03:30:00	22177 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string warehouse {
            get {
                return ResourceManager.GetString("warehouse", resourceCulture);
            }
        }
    }
}
